spring:
  datasource:
    # Monta a URL de conexão casando perfeitamente com os nomes das variáveis do Render
    url: jdbc:postgresql://${RENDER_POSTGRES_HOST}:${RENDER_POSTGRES_PORT:5432}/${RENDER_POSTGRES_DB}?sslmode=require
    username: ${RENDER_POSTGRES_USER}
    password: ${RENDER_POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # O bloco 'properties' com o dialect antigo foi completamente removido daqui!
