spring:
  datasource:
    # CORRIGIDO: Injeta a URL do Render adicionando a propriedade de SSL obrigatória para produção
    url: jdbc:${DATABASE_URL}?sslmode=require
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
